# Generated by Django 3.1 on 2020-09-03 10:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=165, null=True, verbose_name='СЕО  Заголовок')),
                ('readableTitle', models.CharField(blank=True, max_length=165, null=True, verbose_name='Читаемый заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='СЕО Описание(скрытое)')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='СЕО Ключевые слова')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст на странице')),
            ],
            options={
                'verbose_name': 'Страницу СЕО',
                'verbose_name_plural': 'Страницы и СЕО',
            },
        ),
    ]
