# Generated by Django 3.1 on 2020-09-03 13:06

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200903_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=50, verbose_name='Название')),
                ('categoryImage', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='readableTitle',
            field=models.CharField(blank=True, max_length=165, null=True, verbose_name='Заголовок на странице'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.inpageimages', verbose_name='Изображения'),
        ),
    ]
