# Generated by Django 3.1 on 2020-09-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200903_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='image',
        ),
        migrations.AddField(
            model_name='inpageimages',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.indexpage', verbose_name='Страница'),
        ),
    ]
