# Generated by Django 3.1 on 2020-09-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200903_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='Page',
        ),
    ]
