# Generated by Django 3.1 on 2020-09-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200903_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpageimages',
            name='page',
            field=models.ForeignKey(default='/static/frontend/images/placeholder.png', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Страница'),
        ),
    ]
