# Generated by Django 3.1 on 2020-09-07 15:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200903_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Фото наших работ',
                'verbose_name_plural': 'Фото наших работ',
            },
        ),
        migrations.AlterField(
            model_name='inpageimages',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='inpageimages',
            name='ourWorks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ourworks', verbose_name='Наши работы'),
        ),
    ]
