# Generated by Django 3.1.1 on 2020-09-27 10:23

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_ourworks_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourworks',
            options={'verbose_name': 'Фото наших работ', 'verbose_name_plural': 'Галерея наших работ'},
        ),
        migrations.RemoveField(
            model_name='inpageimages',
            name='categoryImage',
        ),
        migrations.AddField(
            model_name='inpageimages',
            name='pageImage',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ourworks',
            name='category',
            field=models.CharField(choices=[('ALL', 'Без категории'), ('UT', 'Смеси для утепления'), ('PO', 'Смеси для пола'), ('KL', 'Кладочные смеси'), ('OB', 'Смеси для облицовки'), ('SH', 'Штукатурные смеси')], default='ALL', max_length=10, null=True, verbose_name='Категория'),
        ),
    ]
